language: d
sudo: false


matrix:
  include:
    - d: dmd-nightly
    - d: dmd-2.093.0
    - d: dmd-2.092.1
  allow_failures:
    - d: dmd-nightly

script:
  - build/ci.sh
  # - dub build -b ddox


after_success:
 - bash <(curl -s https://codecov.io/bash)
